name: warzone2100
adopt-info: warzone2100
summary: A free and open source real time strategy game
icon: icons/warzone2100.large.png
license: GPL-2.0+
description: |
  In Warzone 2100, you command the forces of The Project in a battle to rebuild the world after mankind has almost been destroyed by nuclear missiles.

  The game offers campaign, multi-player, and single-player skirmish modes. An extensive tech tree with over 400 different technologies, combined with the unit design system, allows for a wide variety of possible units and tactics.

  Warzone 2100 was originally developed as a commercial game by Pumpkin Studios and published in 1999, and was released as open source by them in 2004, for the community to continue working on it.

confinement: strict
grade: stable
base: core18

apps:
  warzone2100:
    command: usr/bin/warzone2100
    command-chain: [bin/desktop-launch]
    plugs:
      - audio-playback
      - desktop
      - desktop-legacy
      - network
      - network-bind
      - opengl
      - pulseaudio
      - unity7
      - wayland
      - x11

  download-videos:
    command: bin/download-videos
    plugs: [network]

parts:
  scripts:
    plugin: dump
    source: scripts
    override-build: |
      chmod +x download-videos
      snapcraftctl build
    organize:
      download-videos: bin/download-videos
    stage-packages:
      - curl

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: qt
    plugin: make
    make-parameters: ["FLAVOR=qt5"]
    build-packages:
      - qtbase5-dev
      - dpkg-dev
    stage-packages:
      - libxkbcommon0
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - gnome-themes-standard
      - shared-mime-info
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5 # for loading icon themes which are svg
      - qtwayland5
      - try: [appmenu-qt5] # not available on core18
      - locales-all
      - libgtk2.0-0

  sdl:
    source: https://www.libsdl.org/release/SDL2-2.0.10.tar.gz
    plugin: autotools
    configflags:
    - --prefix=/usr
    - --disable-alsa
    - --disable-arts
    - --disable-esd
    - --disable-nas
    - --disable-oss
    build-packages:
    - fcitx-libs-dev
    - libegl1-mesa-dev
    - libgl1-mesa-dev
    - libgles2-mesa-dev
    - libibus-1.0-dev
    - libjack-dev
    - libpulse-dev
    - libsamplerate0-dev
    - libsndfile1-dev
    # - libts-dev # not available in xenial - touch screen library
    - libvulkan-dev
    - libwayland-dev
    - libx11-dev
    - libxcursor-dev
    - libxext-dev
    - libxi-dev
    - libxinerama-dev
    - libxkbcommon-dev
    - libxrandr-dev
    - libxrender-dev
    - libxss-dev
    - libxxf86vm-dev
    stage-packages:
    - fcitx-libs
    - libdrm2
    - libegl1-mesa
    - libgl1
    - libgles2
    - libibus-1.0-5
    - libjack0
    - libpulse0
    - libsamplerate0
    # - libts0 # not available in xenial - touch screen library
    - libsndfile1
    - libwayland-client0
    - libwayland-egl1-mesa
    - libvulkan1
    - libx11-6
    - libxcursor1
    - libxext6
    - libxi6
    - libxinerama1
    - libxkbcommon0
    - libxrandr2
    - libxrender1
    - libxss1
    - libxxf86vm1

  warzone2100:
    after: [desktop-qt5, sdl]
    source: https://github.com/Warzone2100/warzone2100.git
    override-pull: |
      snapcraftctl pull

      last_committed_tag="$(git tag -l --sort=version:refname | grep -E -e '^[1-9]+(\.[0-9]+){2,}' | grep -E -v '[-_](beta([0-9]+)?)' | tail -n 1)"
      echo "last_committed_tag: $last_committed_tag"
      last_released_tag="$(snap info warzone2100 | awk '$1 == "latest/beta:" { print $2 }')"
      echo "last_released_tag: $last_released_tag"
      # If the latest tag from the upstream project has not been released to
      # beta, build that tag instead of master.
      if [ "${last_committed_tag}" != "${last_released_tag}" ]; then
        echo "git submodule deinit --all"
        git submodule deinit --all
        echo "git fetch ..."
        git fetch
        echo "git checkout $last_committed_tag ..."
        git checkout "${last_committed_tag}"
        echo "git submodule update"
        git submodule update --init
      fi
      snapcraftctl set-version "$last_committed_tag"
    source-type: git
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=RelWithDebInfo
      - -DWZ_DISTRIBUTOR=Snapcraft
    build-packages:
      - asciidoctor
      - gettext
      - libfontconfig1-dev
      - libfreetype6-dev
      - libfribidi-dev
      - libglc-dev
      - libglew-dev
      - libharfbuzz-dev
      - libopenal-dev
      - libphysfs-dev
      - libpng-dev
      - libtheora-dev
      - libvorbis-dev
      - qtbase5-dev
      - qtscript5-dev
      - libcurl4-gnutls-dev
      - gnutls-dev
      - libsodium-dev
      - unzip
      - zip
    stage-packages:
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libglc0
      - libglew2.0
      - libharfbuzz0b
      - libogg0
      - libopenal1
      - libphysfs1
      - libpng16-16
      - libqt5opengl5
      - libqt5script5
      - libtheora0
      - libvorbis0a
      - libvorbisenc2
      - libvorbisfile3
      - libcurl3-gnutls
      - libsodium23
      - libglu1-mesa
      - unzip
      - zip
